
lang: en

title: rockyyh

description: Welcome to my blog!

url: "https://rockyyh.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
