
lang: en
title: Yinghao Yang
email: yangyinghao@westlake.edu.cn
favicon: true
color-scheme: auto
description: Undergraduate@Westlake University
logo: /assets/img/me.jpg

url: "https://rockyyh.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-scholar

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/rockyyh

navigation:
  - name: Home
    link: /

scholar:
  locale: "en-US"
  style: "ieee"    # 选择引用样式，如 APA, ieee, chicago 等
  canonical: false
  schema: false
  sort: "year"    # 按年份排序
  reverse: true    # 倒序显示
